name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t wisecow-app .
          docker tag wisecow-app:latest ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          
      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube   

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${KUBECONFIG}" | > $HOME/.kube/config
          
      - name: Deploy to Kubernetes
        run: |
          curl -sfL https://get.k3s.io | sh -
          sudo systemctl start k3s
          sudo chown root:root /etc/rancher/k3s/k3s.yaml
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          sudo chmod 755 /etc/rancher/k3s
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f deployment.yml 
          kubectl apply -f service.yml 
          kubectl apply -f ingress.yml 
          kubectl get ingress
          kubectl get services --namespace ingress-nginx
          kubectl get services




